[package]
name = "djade"
version = "1.6.0"
edition = "2024"
readme = "README.rst"
default-run = "djade"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
regex = "1.10.6"
toml = "0.8"

[dev-dependencies]
tempfile = "3.12.0"
